### ISSUE TITLE
Aonde colocar meus links?

### ISSUE THREAD

**Issue by lucasalbuquerque** [rodrigokono/comecandodozero#10]
Oi Rodrigo, seguem os links das primeiras vídeo aulas que criei, queria saber aonde devo colocar? Existe um arquivo especifico para listar as vídeo aulas de cada um? Abs

<a href="https://www.youtube.com/watch?v=RO6zOS0ngmk">01 - Instalando o Visual Studio Code</a>

<a href="https://www.youtube.com/watch?v=-eygU58z6vg">02 - Recursos básicos do Visual Studio Code</a>

<a href="https://www.youtube.com/watch?v=Dqsb_FgVYo0">03 - Primeiros passos com HTML</a>

<a href="https://www.youtube.com/watch?v=_7UuMhArF-Q">04 - Inspercionar elemento e testar Responsividade</a>

**Comment by rodrigokono** [comment]
Oi Lucas.
Ficou muito bom. Mas acho que o audio ficou super baixo. Tem como você arrumá-los? Acho que o youtube tem uma ferramenta q ajuda a melhorar o audio.

Sobre o local pra adicionar, veja o de "GIT" que foi adicionado hoje. Dauqela forma.
Nesse caso temos 2 de VS Code, 2 de HTML
