### ISSUE TITLE
Link correto

### ISSUE THREAD

**Issue by programadriano** [rodrigokono/comecandodozero#7]
Ola Rodrigo ... eu criei um vídeo, subi no Youtube com a # solicitada, gostaria de confirmar com você se subi da maneira correta? quando subirem videos relacionados a git irei ver estou viciado no TFS rs 
abs,

**Comment by rodrigokono** [comment]
Opa! Manda aqui no PR.

**Comment by programadriano** [comment]
Opa subi vlw

**Comment by rodrigokono** [comment]
Opa. Valeu! Vi o PR. Você pode colocar ele como um link dentro da area do VS na tabela. Como "Baixando VS e criando um projeto". Outro ponto é que faltou sua narração. Mas está valendo.

**Comment by programadriano** [comment]
opa vlw, comprei um fone melhor para gravar... partiu saga do casaco hehehe  abs

**Comment by programadriano** [comment]
Boa noite Rodrigo, eu corrigi o link e subi mais alguns, queria confirmar com voce se estão OK? e se podemos subir tutoriais como: c# com operações matemáticas, integração com Api's, Web Api ... etc?
